'-------------------------------------------------------------------------------
' Copyright (c) 2021-2022, Arm Limited and Contributors. All rights reserved.
'
' SPDX-License-Identifier: BSD-3-Clause
'
'-------------------------------------------------------------------------------

@startuml

[u-boot efi services] -down- [smm gateway]
[smm gateway] -down- [secure storage service]
[smm gateway] -down- [crypto service]

@enduml
