'-------------------------------------------------------------------------------
' Copyright (c) 2024, Arm Limited and Contributors. All rights reserved.
'
' SPDX-License-Identifier: BSD-3-Clause
'
'-------------------------------------------------------------------------------

@startuml
participant "PSA FWU A Update Client" as client
participant "PSA FWU A Update Agent" as agent
participant "PSA FWU M Service" as service

autoactivate on

client -> agent: fwu_begin_staging()

alt state == Staging
	agent -> agent: fwu_cancel_staging()
	agent --> agent

	loop on all images
		agent -> service: psa_fwu_clean(image)
		service --> agent
	end
end

loop on selected images
	agent -> service: psa_fwu_start(image)
	service --> agent
end

hnote over agent: state = Staging

agent --> client

@enduml
