'-------------------------------------------------------------------------------
' Copyright (c) 2020-2021, Arm Limited and Contributors. All rights reserved.
'
' SPDX-License-Identifier: BSD-3-Clause
'
'-------------------------------------------------------------------------------

@startuml

class rpc_caller {
	{abstract}int call(opcode, param_buf, result_buf)
}

rpc_caller -> call_ep
note right on link
Association with call_ep is made when
RPC session is established.
end note

@enduml