'-------------------------------------------------------------------------------
' Copyright (c) 2020-2021, Arm Limited and Contributors. All rights reserved.
'
' SPDX-License-Identifier: BSD-3-Clause
'
'-------------------------------------------------------------------------------

' Colors shared between various graphs

!define COLOR_ARM_BLUE #0091BD
!define COLOR_LT_BLUE b3edff

' The higher the number at the end of the name the darker the color is.
!define COLOR_BLUE1 #DCEEF3
!define COLOR_BLUE2  #B9DDE7
!define COLOR_BLUE3  #96CDDB
!define COLOR_GREEN1 #EBF1E0
!define COLOR_GREEN2 #DEF2B8
!define COLOR_GREY1  #D9D9D9
!define COLOR_GREY2  #F2F2F2
!define COLOR_RED1   #FF9C9C
!define COLOR_RED2   #FFD6D6

!define COLOR_PSA_NW               COLOR_GREY1
!define COLOR_PSA_S_APP_ROT        COLOR_GREEN1
!define COLOR_PSA_S_PSA_ROT        COLOR_BLUE2
!define COLOR_PSA_S_ROT_PERIPHERAL COLOR_BLUE1
!define COLOR_PSA_NS_PE            COLOR_NW
!define COLOR_PSA_FW_API           COLOR_RED2
!define COLOR_PSA_ROT_SERVICE_API  COLOR_RED1
